services:
  - type: web
    name: lebrume-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_EXPIRES_IN
        value: 1d
      - key: CORS_ORIGIN
        value: https://lebrume.com.au
    # As seguintes variáveis devem ser configuradas no painel do Render:
    # DB_HOST, DB_PORT, DB_USERNAME, DB_PASSWORD, DB_DATABASE, JWT_SECRET

